### ISSUE TITLE
[audit gitlab] undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by bxscif** [github/gh-actions-importer#114]
```
❯ gh actions-importer version                                                     
gh version 2.28.0 (2023-04-25)
gh actions-importer     github/gh-actions-importer      v1.2.2
actions-importer/cli:latest     v1.2.18472
```

```
❯ gh actions-importer audit gitlab --no-telemetry --no-http-cache -o audit -n core 
[2023-04-26 23:15:14] Logs: 'audit/log/valet-20230426-231514.log'
[2023-04-26 23:15:14] Auditing 'https://gitlab.selfhosted.local/core'
[2023-04-26 23:15:18] There was an error extracting the GitLab CI pipeline (core/legacy-auth-adapter)
                      Message: (GET 403) Forbidden: https://gitlab.selfhosted.local/api/v4/projects/core%2Flegacy-auth-adapter/variables
[2023-04-26 23:15:38] Unable to find child pipeline: '[{"artifact"=>"child-pipeline-gitlab-ci.yml", "job"=>"iac-generate-pipeline"}]'
[2023-04-26 23:15:40] Unable to find child pipeline: '[{"artifact"=>"child-pipeline-gitlab-ci.yml", "job"=>"iac-generate-pipeline"}]'
[2023-04-26 23:15:41] Output file(s):==========================================|
[2023-04-26 23:15:41]   audit/core/legacy-auth-adapter/error.txt
[2023-04-26 23:15:41]   audit/core/website-settings/.github/workflows/website-settings.yml
[2023-04-26 23:15:41]   audit/core/website-settings/config.json
[2023-04-26 23:15:41]   audit/core/website-settings/source.yml
[2023-04-26 23:15:41]   audit/core/text-optout/.github/workflows/text-optout.yml
[2023-04-26 23:15:41]   audit/core/text-optout/config.json
[2023-04-26 23:15:41]   audit/core/text-optout/source.yml
[2023-04-26 23:15:41] undefined method `[]' for nil:NilClass

❯ 
```

**Comment by bxscif** [comment]
Stack trace for the error...
```
E, [2023-04-26T23:15:41.631853 #1] ERROR -- : undefined method `[]' for nil:NilClass
/usr/local/bundle/gems/actions_importer-1.2.18472/lib/valet/models/github/workflow.rb:40:in `block in composite_actions'
/usr/local/bundle/gems/actions_importer-1.2.18472/lib/valet/models/github/workflow.rb:37:in `each'
/usr/local/bundle/gems/actions_importer-1.2.18472/lib/valet/models/github/workflow.rb:37:in `map'
/usr/local/bundle/gems/actions_importer-1.2.18472/lib/valet/models/github/workflow.rb:37:in `composite_actions'
/usr/local/bundle/gems/actions_importer-1.2.18472/lib/valet/models/base/transform_pipeline/result/single.rb:61:in `composite_actions'
/usr/local/bundle/gems/actions_importer-1.2.18472/lib/valet/models/base/transform_pipeline/result/single.rb:46:in `block in files'
<internal:kernel>:90:in `tap'
/usr/local/bundle/gems/actions_importer-1.2.18472/lib/valet/models/base/transform_pipeline/result/single.rb:39:in `files'
/usr/local/bundle/gems/actions_importer-1.2.18472/lib/valet/commands/audit.rb:42:in `block in call'
/usr/local/bundle/gems/actions_importer-1.2.18472/lib/valet/commands/audit.rb:40:in `each'
/usr/local/bundle/gems/actions_importer-1.2.18472/lib/valet/commands/audit.rb:40:in `call'
/usr/local/bundle/gems/actions_importer-1.2.18472/lib/valet/subcommands/audit.rb:130:in `gitlab'
/usr/local/bundle/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
/usr/local/bundle/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
/usr/local/bundle/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
/usr/local/bundle/gems/thor-1.2.1/lib/thor/invocation.rb:116:in `invoke'
/usr/local/bundle/gems/thor-1.2.1/lib/thor.rb:243:in `block in subcommand'
/usr/local/bundle/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
/usr/local/bundle/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
/usr/local/bundle/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
/usr/local/bundle/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
/usr/local/bundle/gems/actions_importer-1.2.18472/exe/actions-importer:19:in `<top (required)>'
/usr/local/bundle/bin/actions-importer:25:in `load'
/usr/local/bundle/bin/actions-importer:25:in `<main>'
```

**Comment by j-dunham** [comment]
Hi @bxscif,  

GitHub Actions Importer does not support transforming  a child pipeline that is dynamically created in a pipeline.   The child pipeline needs to exist at transformation time so it can be added to the resulting Actions workflow.   I have just merged a change so the rest of the pipeline should continue to be transform even though the child pipeline cannot be found.   You can get this change by doing `gh actions-importer update` and then retrying.
