### ISSUE TITLE
Api.github.com error when doing migration (execution expired)

### ISSUE THREAD

**Issue by jhwal47** [github/gh-actions-importer#228]
### Discussed in https://github.com/github/gh-actions-importer/discussions/226

<div type='discussions-op-text'>

<sup>Originally posted by **jhwal47** August  7, 2023</sup>
Hi, I’m having an issue running a gitlab -> github migration with api.github.com:443 call. 

I’m able to perform the call successfully with a curl : 

curl -X GET  -u $GITHUB_TOKEN:x-oauth-basic  https://api.github.com/repos/<my-repo> 

And this successfully returns the info. 

I have used gh actions-importer configure, and I have also the the github token in the command line. Neither works. 

Log output: 
I, [2023-08-07T19:16:42.133039 #1]  INFO -- request: GET https://api.github.com/repos/<my-repo>
I, [2023-08-07T19:17:42.198274 #1]  INFO -- request: GET https://api.github.com/user
E, [2023-08-07T19:18:42.298208 #1] ERROR -- : Failed to open TCP connection to api.github.com:443 (execution expired)
/usr/local/lib/ruby/3.2.0/net/http.rb:1271:in `initialize'
/usr/local/lib/ruby/3.2.0/net/http.rb:1271:in `open'
/usr/local/lib/ruby/3.2.0/net/http.rb:1271:in `block in connect'
/usr/local/lib/ruby/3.2.0/timeout.rb:189:in `block in timeout'
/usr/local/lib/ruby/3.2.0/timeout.rb:196:in `timeout'
/usr/local/lib/ruby/3.2.0/net/http.rb:1269:in `connect'
/usr/local/lib/ruby/3.2.0/net/http.rb:1248:in `do_start'
/usr/local/lib/ruby/3.2.0/net/http.rb:1237:in `start'
/usr/local/bundle/gems/faraday-net_http-3.0.2/lib/faraday/adapter/net_http.rb:112:in `request_with_wrapped_block'
/usr/local/bundle/gems/faraday-net_http-3.0.2/lib/faraday/adapter/net_http.rb:102:in `perform_request'
/usr/local/bundle/gems/faraday-net_http-3.0.2/lib/faraday/adapter/net_http.rb:66:in `block in call'
/usr/local/bundle/gems/faraday-2.7.2/lib/faraday/adapter.rb:45:in `connection'
/usr/local/bundle/gems/faraday-net_http-3.0.2/lib/faraday/adapter/net_http.rb:65:in `call'
/usr/local/bundle/gems/faraday-2.7.2/lib/faraday/middleware.rb:17:in `call'
/usr/local/bundle/gems/faraday-2.7.2/lib/faraday/middleware.rb:17:in `call'
/usr/local/bundle/gems/faraday-http-cache-2.5.0/lib/faraday/http_cache.rb:286:in `fetch'
/usr/local/bundle/gems/faraday-http-cache-2.5.0/lib/faraday/http_cache.rb:190:in `process'
/usr/local/bundle/gems/faraday-http-cache-2.5.0/lib/faraday/http_cache.rb:141:in `call!'
/usr/local/bundle/gems/faraday-http-cache-2.5.0/lib/faraday/http_cache.rb:121:in `call'
/usr/local/bundle/gems/faraday-2.7.2/lib/faraday/middleware.rb:17:in `call'
/usr/local/bundle/gems/faraday-2.7.2/lib/faraday/response/logger.rb:23:in `call'
/usr/local/bundle/gems/faraday-2.7.2/lib/faraday/middleware.rb:17:in `call'
/usr/local/bundle/gems/faraday-2.7.2/lib/faraday/middleware.rb:17:in `call'</div>

**Comment by jhwal47** [comment]
I’ve tried with fine grained ans classic tokens.

**Comment by begonaguereca** [comment]
Hi @jhwal47! So sorry to hear that you've been experiencing some troubles. In this scenario I am going to ask that you please open up a support ticket [here](https://support.github.com/) 🙏🏽

**Comment by jhwal47** [comment]
Thanks Begona! 

Appreciated the quick reply, I did create an issue for it.. This one had me stumped. 



https://github.com/github/gh-actions-importer/issues/228￼
Api.github.com error when doing migration (execution expired) · Issue #228 · github/gh-actions-importer
github.com

Please let me know if I can provide further information..

Jim

**Comment by jhwal47** [comment]
Thx again - 

https://support.github.com/ticket/personal/0/2284184

**Comment by jhwal47** [comment]
I found the issue! I was using the env var https_proxy I need to use HTTPS_PROXY. 
Gad..
