### ISSUE TITLE
[Support]: Got http 422 from Github API

### ISSUE THREAD

**Issue by DanSnow** [github/gh-actions-importer#30]
### What operating system are you using?

- [ ] Linux
- [X] macOS
- [ ] Windows

### What version of the tool are you using?

gh version 2.20.2 (2022-11-15)
gh actions-importer	github/gh-actions-importer	v1.0.1
actions-importer/cli	v1.0.14669

### What happened?

Output error when running
```plain
gh actions-importer migrate circle-ci -o .github --target-url https://github.com/<owner>/<repo> --circle-ci-project <repo>
```

### Relevant log output

```shell
I, [2022-12-17T13:58:13.209157 #1]  INFO -- response: Status 422
I, [2022-12-17T13:58:13.286947 #1]  INFO -- : Sending telemetry with transaction id '706075e5-837a-478d-9a5d-19f2f61550c5'
E, [2022-12-17T13:58:14.207451 #1] ERROR -- : (PUT 422) Unprocessable Entity: https://api.github.com/repos/<owner>/<repo>/contents/.github/actions/slack_notify/action.yml
Message: Invalid request.

"sha" wasn't supplied.
/usr/local/bundle/gems/octokit-5.6.1/lib/octokit/response/raise_error.rb:14:in `on_complete'
/usr/local/bundle/gems/faraday-1.7.1/lib/faraday/middleware.rb:19:in `block in call'
/usr/local/bundle/gems/faraday-1.7.1/lib/faraday/response.rb:59:in `on_complete'
/usr/local/bundle/gems/faraday-1.7.1/lib/faraday/middleware.rb:18:in `call'
/usr/local/bundle/gems/octokit-5.6.1/lib/octokit/middleware/follow_redirects.rb:73:in `perform_with_redirection'
/usr/local/bundle/gems/octokit-5.6.1/lib/octokit/middleware/follow_redirects.rb:61:in `call'
/usr/local/bundle/gems/faraday-1.7.1/lib/faraday/request/retry.rb:148:in `call'
/usr/local/bundle/gems/faraday-1.7.1/lib/faraday/rack_builder.rb:154:in `build_response'
/usr/local/bundle/gems/faraday-1.7.1/lib/faraday/connection.rb:511:in `run_request'
/usr/local/bundle/gems/faraday-1.7.1/lib/faraday/connection.rb:281:in `put'
/usr/local/bundle/gems/sawyer-0.9.2/lib/sawyer/agent.rb:99:in `call'
/usr/local/bundle/gems/octokit-5.6.1/lib/octokit/connection.rb:156:in `request'
/usr/local/bundle/gems/octokit-5.6.1/lib/octokit/connection.rb:37:in `put'
/usr/local/bundle/gems/octokit-5.6.1/lib/octokit/client/contents.rb:86:in `create_contents'
/usr/local/bundle/gems/actions_importer-1.0.14669/lib/valet/services/github/submit_workflow.rb:151:in `rescue in upsert_contents'
/usr/local/bundle/gems/actions_importer-1.0.14669/lib/valet/services/github/submit_workflow.rb:138:in `upsert_contents'
/usr/local/bundle/gems/actions_importer-1.0.14669/lib/valet/services/github/submit_workflow.rb:70:in `block in call'
/usr/local/bundle/gems/actions_importer-1.0.14669/lib/valet/services/github/submit_workflow.rb:69:in `each'
/usr/local/bundle/gems/actions_importer-1.0.14669/lib/valet/services/github/submit_workflow.rb:69:in `call'
/usr/local/bundle/gems/actions_importer-1.0.14669/lib/valet/commands/migrate.rb:21:in `block in call'
/usr/local/bundle/gems/actions_importer-1.0.14669/lib/valet/logger.rb:88:in `with_progress_bar'
/usr/local/bundle/gems/actions_importer-1.0.14669/lib/valet/commands/migrate.rb:20:in `call'
/usr/local/bundle/gems/actions_importer-1.0.14669/lib/valet/subcommands/migrate.rb:79:in `circle_ci'
/usr/local/bundle/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
/usr/local/bundle/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
/usr/local/bundle/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
/usr/local/bundle/gems/thor-1.0.1/lib/thor/invocation.rb:116:in `invoke'
/usr/local/bundle/gems/thor-1.0.1/lib/thor.rb:243:in `block in subcommand'
/usr/local/bundle/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
/usr/local/bundle/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
/usr/local/bundle/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
/usr/local/bundle/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
/usr/local/bundle/gems/actions_importer-1.0.14669/exe/actions-importer:16:in `<top (required)>'
/usr/local/bundle/bin/actions-importer:23:in `load'
/usr/local/bundle/bin/actions-importer:23:in `<main>'
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by DanSnow** [comment]
BTW, I noticed that the github action failed to run on this issue https://github.com/github/gh-actions-importer/actions/runs/3720382733/jobs/6309823792

**Comment by ethanis** [comment]
@DanSnow sorry to hear you're running into this issue! We'll take a look at things on our end to see what may have happened.

Can you confirm that the repository that's being migrated to exists and has had at least 1 commit?

**Comment by DanSnow** [comment]
Yes. I can paste more logs here. The failed request is not the first one

```plain
I, [2022-12-17T13:58:06.659489 #1]  INFO -- request: GET https://api.github.com/repos/<owner>/<repo>
I, [2022-12-17T13:58:07.191164 #1]  INFO -- response: Status 200
I, [2022-12-17T13:58:07.215787 #1]  INFO -- request: GET https://api.github.com/repos/<owner>/<repo>/git/refs/heads/dev
I, [2022-12-17T13:58:07.660013 #1]  INFO -- response: Status 200
I, [2022-12-17T13:58:07.669897 #1]  INFO -- request: POST https://api.github.com/repos/<owner>/<repo>/git/refs
I, [2022-12-17T13:58:08.315031 #1]  INFO -- response: Status 201
I, [2022-12-17T13:58:08.877453 #1]  INFO -- request: GET https://api.github.com/repos/<owner>/<repo>/contents/.github/workflows/node-test.yml?sha=48a4f39b460001d60d2fa3f63a40e79097d6ee23
I, [2022-12-17T13:58:09.334335 #1]  INFO -- response: Status 404
I, [2022-12-17T13:58:09.344564 #1]  INFO -- request: PUT https://api.github.com/repos/<owner>/<repo>/contents/.github/workflows/node-test.yml
I, [2022-12-17T13:58:10.013130 #1]  INFO -- response: Status 201
I, [2022-12-17T13:58:10.031332 #1]  INFO -- request: GET https://api.github.com/repos/<owner>/<repo>/contents/.github/actions/slack_notify/action.yml?sha=48a4f39b460001d60d2fa3f63a40e79097d6ee23
I, [2022-12-17T13:58:10.520579 #1]  INFO -- response: Status 404
I, [2022-12-17T13:58:10.528870 #1]  INFO -- request: PUT https://api.github.com/repos/<owner>/<repo>/contents/.github/actions/slack_notify/action.yml
I, [2022-12-17T13:58:11.181005 #1]  INFO -- response: Status 201
I, [2022-12-17T13:58:11.201305 #1]  INFO -- request: GET https://api.github.com/repos/<owner>/<repo>/contents/.github/workflows/deploy-production.yml?sha=48a4f39b460001d60d2fa3f63a40e79097d6ee23
I, [2022-12-17T13:58:11.685405 #1]  INFO -- response: Status 404
I, [2022-12-17T13:58:11.695889 #1]  INFO -- request: PUT https://api.github.com/repos/<owner>/<repo>/contents/.github/workflows/deploy-production.yml
I, [2022-12-17T13:58:12.652169 #1]  INFO -- response: Status 201
I, [2022-12-17T13:58:12.670045 #1]  INFO -- request: GET https://api.github.com/repos/<owner>/<repo>/contents/.github/actions/slack_notify/action.yml?sha=48a4f39b460001d60d2fa3f63a40e79097d6ee23
I, [2022-12-17T13:58:12.676289 #1]  INFO -- response: Status 404
I, [2022-12-17T13:58:12.681466 #1]  INFO -- request: PUT https://api.github.com/repos/<owner>/<repo>/contents/.github/actions/slack_notify/action.yml
I, [2022-12-17T13:58:13.209157 #1]  INFO -- response: Status 422
I, [2022-12-17T13:58:13.286947 #1]  INFO -- : Sending telemetry with transaction id '706075e5-837a-478d-9a5d-19f2f61550c5'
E, [2022-12-17T13:58:14.207451 #1] ERROR -- : (PUT 422) Unprocessable Entity: https://api.github.com/repos/<owner>/<repo>/contents/.github/actions/slack_notify/action.yml
```

**Comment by ethanis** [comment]
@DanSnow thanks for sending these logs over! We just shipped a new version that will avoid this issue. Can you update Actions Importer (i.e. `gh actions-importer update`) and verify that the same migration command works?

**Comment by DanSnow** [comment]
It works. Awesome
