### ISSUE TITLE
[Support]: migration from GitLab to GitHub Actions problems

### ISSUE THREAD

**Issue by SiPaff** [github/gh-actions-importer#42]
### What operating system are you using?

- [X] Linux
- [ ] macOS
- [ ] Windows

### What version of the tool are you using?

gh version 2.23.0 (2023-02-08)

### What happened?

I have a problem; I'm setting up a Ci/Cd migration from GitLab to GitHub Actions. When performing an audit, it outputs this output.

There was an internal error transforming the GitLab CI pipeline (###/###) into a GitHub Actions workflow.
Please reference 'b1174b86255548671a21b4c45dae98ea1f018a46' when requesting support.

Can you explain to me what I should do next?

### Relevant log output

```shell
Please reference 'REDACTED' when requesting support.
/usr/local/bundle/gems/actions_importer-1.0.16231/lib/valet/services/gitlab_ci/job_graph_builder.rb:10:in `block in <class:JobGraphBuilder>'
/usr/local/bundle/gems/actions_importer-1.0.16231/lib/valet/services/gitlab_ci/job_graph_builder.rb:195:in `merge!'
/usr/local/bundle/gems/actions_importer-1.0.16231/lib/valet/services/gitlab_ci/job_graph_builder.rb:195:in `block (2 levels) in merge_extended_jobs'
/usr/local/bundle/gems/actions_importer-1.0.16231/lib/valet/services/gitlab_ci/job_graph_builder.rb:184:in `each'
/usr/local/bundle/gems/actions_importer-1.0.16231/lib/valet/services/gitlab_ci/job_graph_builder.rb:184:in `block in merge_extended_jobs'
<internal:kernel>:90:in `tap'
/usr/local/bundle/gems/actions_importer-1.0.16231/lib/valet/services/gitlab_ci/job_graph_builder.rb:183:in `merge_extended_jobs'
/usr/local/bundle/gems/actions_importer-1.0.16231/lib/valet/services/gitlab_ci/job_graph_builder.rb:121:in `resolve_inherited_values_for_job'
/usr/local/bundle/gems/actions_importer-1.0.16231/lib/valet/services/gitlab_ci/job_graph_builder.rb:107:in `block in resolve_inherited_values_for_jobs!'
/usr/local/bundle/gems/actions_importer-1.0.16231/lib/valet/services/gitlab_ci/job_graph_builder.rb:107:in `transform_values!'
/usr/local/bundle/gems/actions_importer-1.0.16231/lib/valet/services/gitlab_ci/job_graph_builder.rb:107:in `resolve_inherited_values_for_jobs!'
/usr/local/bundle/gems/actions_importer-1.0.16231/lib/valet/services/gitlab_ci/job_graph_builder.rb:28:in `build'
/usr/local/bundle/gems/actions_importer-1.0.16231/lib/valet/transformers/gitlab_ci/jobs.rb:15:in `transform'
/usr/local/bundle/gems/actions_importer-1.0.16231/lib/valet/services/gitlab_ci/transform_pipeline.rb:87:in `call'
/usr/local/bundle/gems/actions_importer-1.0.16231/lib/valet/commands/audit.rb:29:in `block (2 levels) in call'
/usr/local/bundle/gems/actions_importer-1.0.16231/lib/valet/commands/audit.rb:28:in `map'
/usr/local/bundle/gems/actions_importer-1.0.16231/lib/valet/commands/audit.rb:28:in `block in call'
/usr/local/bundle/gems/actions_importer-1.0.16231/lib/valet/logger.rb:89:in `with_progress_bar'
/usr/local/bundle/gems/actions_importer-1.0.16231/lib/valet/commands/audit.rb:27:in `call'
/usr/local/bundle/gems/actions_importer-1.0.16231/lib/valet/subcommands/audit.rb:130:in `gitlab'
/usr/local/bundle/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
/usr/local/bundle/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
/usr/local/bundle/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
/usr/local/bundle/gems/thor-1.2.1/lib/thor/invocation.rb:116:in `invoke'
/usr/local/bundle/gems/thor-1.2.1/lib/thor.rb:243:in `block in subcommand'
/usr/local/bundle/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
/usr/local/bundle/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
/usr/local/bundle/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
/usr/local/bundle/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
/usr/local/bundle/gems/actions_importer-1.0.16231/exe/actions-importer:19:in `<top (required)>'
/usr/local/bundle/bin/actions-importer:25:in `load'
/usr/local/bundle/bin/actions-importer:25:in `<main>'
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ethanis** [comment]
@SiPaff sorry to see you're running into this! Can you open a support ticket [here](https://support.github.com/contact?tags=actions_importer_beta) so we can look into getting this addressed?
